name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create build directory
      run: mkdir -p build

    - name: Run CMake
      working-directory: build
      run: cmake .. -DSTATIC_QUEUE_TEST=ON

    - name: Build the project
      working-directory: build
      run: make

    - name: Run tests
      working-directory: build
      run: ./test_static_queue
